{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - {{- with .Values.ingress.frontend.host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.frontend.path }}
            pathType: {{ .Values.ingress.frontend.pathType }}
            backend:
              service:
                name: frontend
                port:
                  name: http
{{- if and .Values.zipkin.enabled .Values.ingress.zipkin.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - {{- with .Values.ingress.zipkin.host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.zipkin.path }}
            pathType: {{ .Values.ingress.zipkin.pathType }}
            backend:
              service:
                name: zipkin
                port:
                  name: http
{{- end }}
{{- end }}
