{{- if .Values.openshift.routes.enabled }}
{{- if .Values.openshift.routes.frontend.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: http
  {{- with .Values.openshift.routes.frontend.host }}
  host: {{ . | quote }}
  {{- end }}
  {{- with .Values.openshift.routes.frontend.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.zipkin.enabled .Values.openshift.routes.zipkin.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: zipkin
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: zipkin
  port:
    targetPort: http
  {{- with .Values.openshift.routes.zipkin.host }}
  host: {{ . | quote }}
  {{- end }}
  {{- with .Values.openshift.routes.zipkin.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
