{{- if .Values.serviceAccount.create }}
# Create a ServiceAccount for zipkin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
---
# Create ServiceAccounts for each application service
{{- range $name := keys .Values.services | sortAlpha }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}
{{- end }}

# Made with Bob
