nameOverride: ""
fullnameOverride: ""

image:
  repository: py-zipkin-demo
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

consul:
  connectInject: true
  transparentProxy: true

serviceAccount:
  create: true
  name: ""

zipkin:
  image:
    repository: openzipkin/zipkin
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9411
  resources: {}

services:
  serviceA:
    port: 8091
    service:
      type: ClusterIP
    resources: {}
  serviceB:
    port: 8092
    service:
      type: ClusterIP
    resources: {}
  serviceC:
    port: 8093
    service:
      type: ClusterIP
    resources: {}
