{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-demo.fullname" . }}-zipkin
  labels:
    {{- include "python-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: zipkin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-demo.fullname" . }}-service-a
  labels:
    {{- include "python-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-demo.fullname" . }}-service-b
  labels:
    {{- include "python-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-demo.fullname" . }}-service-c
  labels:
    {{- include "python-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-c
{{- end }}
